version: '3'

services:
  # Proxies requests to internal services
  nginx:
    image: nginx:1.20.2
    container_name: nginx_multiple_websites
    restart: always
    depends_on:
      - demo
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 90:80
    networks:
      - redis_redis-network

# demo
  demo:
    image: demo
    container_name: demo
    restart: always
    build:
      context: ./demo
    volumes:
      - './demo:/demo'
    ports:
      - 8080:8080
    environment:
      FLASK_ENV: development  # Enable Flask development mode (auto-reload)
    networks:
      - redis_redis-network

networks: 
  redis_redis-network:
    external: true
